/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ProjetoJogoDeCorridaEmJavaComOO;;

public class App {
    
        public static void main (String[] args ){
            Veiculo fusca = new Veiculo(new MotorFusca());
            Veiculo ferrari = new Veiculo(new MotorFerrari());
            Veiculo lamborguini = new Veiculo (new MotorLamborguini());
            
            System.out.println(fusca.acelerar());
            System.out.println(ferrari.acelerar());
            System.out.println(lamborguini.acelerar());
        }
}

    
